"""
Project 2: Personal Finance Tracker
Entry point. Run with: python main.py
"""

import logging
import os

from transaction import Transaction
from budget import Budget
from tracker import FinanceTracker
from exceptions import InvalidTransactionError, BudgetExceededError

# =======================================================================

# TODO: Configure logging (console INFO + file DEBUG)
logger = logging.getLogger("FinanceTracker")

logger.setLevel(
    logging.DEBUG
)  # This line is not strictly necessary since we set levels on the handlers, but it ensures that all messages are processed by the logger and then filtered by the handlers based on their levels.

# console handler for INFO level
# what is the console handler?
# The console handler is a logging handler that outputs log messages to the console (standard output).
# It allows you to see log messages in real-time as they are generated by your application.
# In this code, we create a console handler that is set to the INFO level, meaning it will display log messages that are at the INFO level or higher (e.g., WARNING, ERROR, CRITICAL) in the console.

console_handler = logging.StreamHandler()
console_handler.setLevel(logging.INFO)
console_formatter = logging.Formatter("%(asctime)s - %(levelname)s - %(message)s")
console_handler.setFormatter(console_formatter)
logger.addHandler(console_handler)


# file handler for DEBUG level
# what is the file handler?
# The file handler is a logging handler that outputs log messages to a file.
# It allows you to save log messages for later analysis or debugging.
# In this code, we create a file handler that is set to the DEBUG level, meaning it will capture all log messages at the DEBUG level and above (including INFO, WARNING, ERROR, CRITICAL) and write them to a file named "finance_tracker.log".
# This way, you can have a detailed record of all events and actions that occur in your application for troubleshooting purposes.

file_handler = logging.FileHandler(
    "logs/finance_tracker.log"
)  # specifies the file where log messages will be written. The logs will be saved in a directory named "logs" with the filename "finance_tracker.log". If the "logs" directory does not exist, it will be created when the file handler is initialized.
file_handler.setLevel(logging.DEBUG)
file_formatter = logging.Formatter("%(asctime)s - %(levelname)s - %(message)s")
file_handler.setFormatter(file_formatter)
logger.addHandler(file_handler)

# =======================================================================


# MAIN APPLICATION LOGIC BELOW
def display_menu():
    print("\n" + "=" * 50)
    print("   Personal Finance Tracker")
    print("=" * 50)
    print("1. Add a transaction")
    print("2. View all transactions")
    print("3. View transactions by category")
    print("4. Monthly report")
    print("5. Set a budget limit")
    print("6. Budget status")
    print("7. Summary by category")
    print("8. Save and exit")
    print("=" * 50)


# =======================================================================


def main():
    tracker = FinanceTracker()

    while True:
        display_menu()
        choice = input("\nEnter your choice (1-8): ").strip()

        # =======================================================================

        if choice == "1":
            # TODO: Prompt for date, amount, category, description, type
            date = input("Enter date (YYYY-MM-DD): ").strip()

            try:
                amount = float(input("Enter amount: ").strip())
            except ValueError:
                print("Invalid amount. Please enter a numeric value.")
                continue

            category = (
                input("Enter category: ").strip().title()
            )  # Using title() to standardize category names (e.g., "Food" instead of "food" or "FOOD").
            description = input("Enter description: ").strip()
            trans_type = input("Enter type (income/expense): ").strip().lower()

            # TODO: Create Transaction and add to tracker
            try:
                transaction = Transaction(
                    date, amount, category, description, trans_type
                )
                tracker.add_transaction(transaction)
            except InvalidTransactionError as e:
                print(f"Error: {e}")
            except BudgetExceededError as e:
                print(
                    f"Warning: {e}"
                )  # This is a warning because the transaction is still added, but the user is notified that it exceeds the budget.

        # =======================================================================

        elif choice == "2":
            # TODO: Display all transactions
            transactions = tracker.transactions
            for transaction in transactions:
                print(transaction)

        # =======================================================================

        elif choice == "3":
            # TODO: Filter by category
            category = input("Enter category to filter: ").strip()
            filtered = tracker.get_transactions_by_category(category)
            for transaction in filtered:
                print(transaction)

        # =======================================================================

        elif choice == "4":
            # TODO: Monthly report
            month = input("Enter month (YYYY-MM): ").strip()
            tracker.monthly_report(month)

        # =======================================================================

        elif choice == "5":
            # TODO: Set budget limit
            month = input("Enter month (YYYY-MM): ").strip()
            category = input("Enter category: ").strip()
            amount = float(input("Enter budget limit: ").strip())
            if month not in tracker.budgets:
                tracker.budgets[month] = Budget(month)
            try:
                tracker.budgets[month].set_limit(category, amount)
                print(f"Budget limit set for {category} in {month}: {amount}")
            except ValueError as e:
                print(f"Error: {e}")

        # =======================================================================

        elif choice == "6":
            # TODO: Budget status
            month = input("Enter month (YYYY-MM): ").strip()
            tracker.budget_status(month)

        # =======================================================================

        elif choice == "7":
            # TODO: Summary by category
            trans_type = (
                input("Enter transaction type (or leave blank): ").strip().lower()
            )
            summary = tracker.summary_by_category(trans_type)
            print(summary)

        # =======================================================================

        elif choice == "8":
            tracker.save_data()
            print("\nData saved. See you later!")
            break
        else:
            print("\nInvalid choice. Please enter a number between 1 and 8.")


# =======================================================================

if __name__ == "__main__":
    main()
